In [7]:
import pandas as pd
import numpy as np
df1 = pd.read_csv('/opt/ml/input/data/pretrained_efficient.csv')
files = ['/opt/ml/input/data/pretrained_efficient.csv', '/opt/ml/input/data/pretrained_efficient.csv']
df2 = pd.read_csv('/opt/ml/input/data/pretrained_efficient.csv')

In [8]:
df1

image_id                                   PredictionString
0    batch_01_vt/0021.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
1    batch_01_vt/0028.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
2    batch_01_vt/0031.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
3    batch_01_vt/0032.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
4    batch_01_vt/0076.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
..                    ...                                                ...
814     batch_03/0968.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
815     batch_03/0969.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
816     batch_03/0992.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
817     batch_03/0998.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
818     batch_03/0999.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...

[819 rows x 2 columns]

In [23]:
tmp = []
tmp1 = list(map(int, df1['PredictionString'][0].split()))
tmp2 = list(map(int, df2['PredictionString'][0].split()))
tmp.append(tmp1)
tmp.append(tmp2)
np.array(tmp).shape

(2, 65536)

In [94]:
lst1 = [0, 0, 1, 1, 2]
lst2 = [1, 1, 1, 1, 1]
lst3 = [1, 0, 0, 0, 2]
lst = [lst1, lst2, lst3]
lst = np.array(lst).T
print(lst)
result = []
for i in range(5):
    result.append(str(np.argmax(np.bincount(np.array(lst)[i]))))
print(' '.join(result))


[[0 1 1]
 [0 1 0]
 [1 1 0]
 [1 1 0]
 [2 1 2]]
1 0 1 1 2


In [105]:
tmpdf = pd.DataFrame(columns=['image_id', 'PredictionString'])
dflist = []
result = []
for file in files:
    dflist.append(pd.read_csv(file))

for i in range(819): 
    result = []
    tmp = []
    for df in range(len(dflist)):
        tmp.append(list(map(int, dflist[df]['PredictionString'][i].split())))

    tmp = np.array(tmp).T
    for k in range(256*256):
        result.append(str(np.argmax(np.bincount(np.array(tmp)[k]))))
    tmpdf = tmpdf.append({'image_id': file_names[i], 'PredictionString':' '.join(result)}, ignore_index=True)
    

In [106]:
tmpdf

image_id                                   PredictionString
0  batch_01_vt/0021.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
1  batch_01_vt/0028.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
2  batch_01_vt/0031.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...

In [107]:
tmpdf

image_id                                   PredictionString
0  batch_01_vt/0021.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
1  batch_01_vt/0028.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
2  batch_01_vt/0031.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...