In [7]:
import pandas as pd
import numpy as np
df1 = pd.read_csv('/opt/ml/input/data/pretrained_efficient.csv')
files = ['/opt/ml/input/data/pretrained_efficient.csv', '/opt/ml/input/data/pretrained_efficient.csv']
df2 = pd.read_csv('/opt/ml/input/data/pretrained_efficient.csv')

In [8]:
df1

image_id                                   PredictionString
0    batch_01_vt/0021.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
1    batch_01_vt/0028.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
2    batch_01_vt/0031.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
3    batch_01_vt/0032.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
4    batch_01_vt/0076.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
..                    ...                                                ...
814     batch_03/0968.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
815     batch_03/0969.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
816     batch_03/0992.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
817     batch_03/0998.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
818     batch_03/0999.jpg  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...

[819 rows x 2 columns]

In [23]:
tmp = []
tmp1 = list(map(int, df1['PredictionString'][0].split()))
tmp2 = list(map(int, df2['PredictionString'][0].split()))
tmp.append(tmp1)
tmp.append(tmp2)
np.array(tmp).shape

(2, 65536)

In [38]:
lst1 = [0, 0, 1, 1, 2]
lst2 = [1, 1, 1, 1, 1]
lst3 = [1, 0, 0, 0, 2]
lst = [lst1, lst2, lst3]
lst = np.array(lst).T
print(lst)
result = []
for i in range(5):
    result.append(np.argmax(np.bincount(np.array(lst)[i])))
print(result)  


[[0 1 1]
 [0 1 0]
 [1 1 0]
 [1 1 0]
 [2 1 2]]
[1, 0, 1, 1, 2]


In [57]:

dflist = []
result = []
for file in files:
    dflist.append(pd.read_csv(file))

for i in range(10): 
    result = []
    tmp = []
    tmp.append(list(map(int, dflist[0]['PredictionString'][i].split())))
    tmp.append(list(map(int, dflist[1]['PredictionString'][i].split())))

    tmp = np.array(tmp).T
    for i in range(256*256):
        result.append(np.argmax(np.bincount(np.array(tmp)[i])))
    tmpdf.append({'image_id': file_names[i], 'PredictionString': ' '.join(list(map(str, np.argmax(np.bincount(np.array(tmp)[i])))))})

IndexError: list index out of range

In [49]:
tmpdf = pd.DataFrame(columns=['image_id', 'PredictionString'])

In [56]:
file_names = list(df1['image_id'])
len(file_names)

819

In [58]:
tmpdf

Empty DataFrame
Columns: [image_id, PredictionString]
Index: []

In [60]:
len(result)

65536

In [ ]:
tmpdf = pd.DataFrame(columns=['image_id', 'PredictionString'])
result = []
for i in range(819):
    predlist = []
    Tlst = []
    for j in range(len(dflist)):
        predlist.append(np.array(list(map(int, dflist[j]['PredictionString'][i].split()))))
    predlist = np.array(predlist).T
    print(predlist.shape)
    for k in range(65536):
        Tlst.append(np.argmax(np.bincount(predlist[i])))
        print(Tlst)
        # Tlst = list(map(str, Tlst))
    tmpdf.append({'image_id':file_names[i], 'PredictionString': Tlst})


(65536, 2)
[0]
[0, 0]
[0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [84]:
tmpdf

Empty DataFrame
Columns: [image_id, PredictionString]
Index: []

In [88]:
i

65535